spring.application.name=demo
spring.datasource.url=jdbc:postgresql://192.168.50.230:5432/munkaerodb
spring.datasource.username=postgres
spring.datasource.password=titok

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.thymeleaf.cache=false