spring.application.name=demo
# PostgreSQL adatbázis kapcsolat (portainer swarm)
spring.datasource.url=jdbc:postgresql://192.168.50.230:5432/munkaerodb
spring.datasource.username=postgres
spring.datasource.password=titok

# JPA / Hibernate beállítások (automatikusan létrehozza a táblákat)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Thymeleaf cache kikapcsolása
spring.thymeleaf.cache=false